[supervisord]
nodaemon=true

[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
autostart=true
autorestart=true
priority=10

[program:backend]
command=/app/venv/bin/python run.py
directory=/app
autostart=true
autorestart=true
priority=20
environment=QE_BIN_PATH="/opt/qe/bin",QE_PSEUDO_PATH="/opt/qe/pseudo",DATABASE_URL="sqlite:////app/data/qe_simulations.db",CORS_ORIGINS="["*"]",PYTHONUNBUFFERED="1"
